chore: roll back the removed `system_prompt` in CLI tool
Signed-off-by: Xin Liu <sam@secondstate.io>

diff --git a/gaianet b/gaianet
--- a/gaianet
+++ b/gaianet
@@ -102,6 +102,12 @@ check_config_options() {
         exit 1
     fi
 
+    # check if the `system_prompt` field exists or not
+    if ! grep -q '"system_prompt":' $gaianet_base_dir/config.json; then
+        error "Not found the 'system_prompt' field in $gaianet_base_dir/config.json\n"
+        exit 1
+    fi
+
     # check if the `embedding` field exists or not
     if ! grep -q '"embedding":' $gaianet_base_dir/config.json; then
         error "Not found the 'embedding' field in $gaianet_base_dir/config.json\n"
@@ -1336,6 +1342,7 @@ show_config_help() {
     printf "  --embedding-ctx-size <val>     Update the context size of embedding model.\n"
     printf "  --prompt-template <val>        Update the prompt template of chat model.\n"
     printf "  --port <val>                   Update the port of LlamaEdge API Server.\n"
+    printf "  --system-prompt <val>          Update the system prompt.\n"
     printf "  --rag-prompt <val>             Update the rag prompt.\n"
     printf "  --rag-policy <val>             Update the rag policy [Possible values: system-message, last-user-message].\n"
     printf "  --reverse-prompt <val>         Update the reverse prompt.\n"
@@ -1400,6 +1407,7 @@ case $subcommand in
         embedding_url=""
         prompt_template=""
         port=""
+        system_prompt=""
         rag_prompt=""
         rag_policy=""
         reverse_prompt=""
@@ -1443,6 +1451,12 @@ case $subcommand in
                 --port)
                     if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
                         port=$2
+                        shift 2
+                    fi
+                    ;;
+                --system-prompt)
+                    if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
+                        system_prompt=$2
                         shift 2
                     fi
                     ;;
@@ -1577,6 +1591,31 @@ case $subcommand in
 
             # update
             update_config llamaedge_port $port
+        fi
+
+        # update system prompt
+        if [ -n "$system_prompt" ]; then
+            printf "[+] Updating the system prompt of chat model ...\n"
+            printf "    * Old system prompt: $(awk -F'"' '/"system_prompt":/ {print $4}' $gaianet_base_dir/config.json)\n"
+            info "    * New system prompt: $system_prompt"
+            # The new value for system_prompt
+            new_value="$system_prompt"
+
+            # Escape ampersands and backslashes in the new value
+            new_value_escaped=$(echo "$new_value" | sed 's/[&\\/]/\\&/g')
+
+            # Update the value of system_prompt in config.json
+            if [ "$(uname)" == "Darwin" ]; then
+                sed -i '' "s|\"system_prompt\": \".*\"|\"system_prompt\": \"$new_value_escaped\"|" $gaianet_base_dir/config.json
+            elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
+                sed -i "s|\"system_prompt\": \".*\"|\"system_prompt\": \"$new_value_escaped\"|" $gaianet_base_dir/config.json
+            elif [ "$(expr substr $(uname -s) 1 10)" == "MINGW32_NT" ]; then
+                error "    * For Windows users, please run this script in WSL."
+                exit 1
+            else
+                error "    * Only support Linux, MacOS and Windows."
+                exit 1
+            fi
         fi
 
         # update rag prompt
